### ISSUE TITLE
Missing key

### ISSUE THREAD

**Issue by PH4NTOMiki** [wesbos/keycodes#231]
When I pressed č it showed "semicolon (firefox), equals", and when I pressed ć it said "single quote / ø / ä"

**Comment by palashmon** [comment]
Thanks for reporting it - What Language is your keyboard?

**Comment by palashmon** [comment]
Closing this issue for now as no response was provided 30 days since the last activity. This is often because the request was already solved in some way and it just wasn't updated or it's no longer applicable. If that's not the case, please do feel free to either reopen this or open a new one. We'll gladly take a look again!
