### ISSUE TITLE
German umlauts not recognized

### ISSUE THREAD

**Issue by JohnArcher** [wesbos/keycodes#3]
Hi!

German umlauts (ä, ö, ü) are not recognized (shown number is 0, text is "huh? ...").

Browser is FF 28.0

Thanks!

**Comment by jancborchardt** [comment]
They are a bit strange to catch, see this [Keycode test page](http://www.asquare.net/javascript/tests/KeyCode.html), the results are like this for a normal letter:
![l](https://cloud.githubusercontent.com/assets/925062/11336879/2f66ec84-91e9-11e5-8c15-07fbd0dfbc99.png)
And this for ö
![ö](https://cloud.githubusercontent.com/assets/925062/11336878/2f644c4a-91e9-11e5-95ef-0180bf0c6ab7.png)

**Comment by vincentdieltiens** [comment]
A serie of keycodes seems to be constant among all keyboards :
 * a -> z
 * arrows
 * numpad(1 -> 9)
 * numpad(=, /, *, - +)
 * home, end, page up, page down, delete, clear
 * tab, shift, ctrl, alt, cmd, enter, backspace

The others depend on the keyboard. 

I see two possibilities :
 * Only allowing the "cross-keyboard keycodes". => For a website, by example
 * Having the possibility to define a keyboard configuration (and having a keyboard mapping for each keyboard). => For a webapp that have a user preference to save the keyboard used by the logged user.

The first one could be used by a shorcut/hotkey library.
I don't see the need of the second possibility ? In which case do we need to know if those chars has been triggered ?

**Comment by wesbos** [comment]
Yeah I'm thinking something like the second one - have an object for each keyboard type and let the user switch between them. Once that is in place, we can just have international users fill everything in for us.

**Comment by vincentdieltiens** [comment]
@wesbos : But what's the need for it ? 
Not for a shortcut/hotkey library because the combination changes depending the keyboard. e.g. : `ctrl+8` for the configuration keyboard and `ctrl+!` for an AZERTY Belgian (apple) keyboard will trigger the same callback.

**Comment by gokaygurcan** [comment]
I was here to open an issue and came across to this one. 

I have a Turkish Q keyboard and Chrome (en). When I try Turkish characters including umlaut they are not getting recognized. 

Here's a list of keys:

| key | result | e.keycode |
| --- | ------- | -----------| 
| ç | back slash | 220 |
| ğ | open bracket | 219 |
| ı * | single quote / ø | 222 |
| ö | forward slash / ç | 191 |
| ş | semi-colon / ñ | 186 |
| ü | close bracket / å | 221 |
| * | ` | 223 |
| print screen | no action | no action |

* this is a nasty one. We have both *ı* and *i* (and also *I* and *İ*) letters in our alphabet. When I press *ı* it shows it as *i* (73), probably because its uppercase form is *I* in English. So, when I press *i* on my keyboard, it thinks that it's a single quote (222).

**Comment by palashmon** [comment]
Hi, thanks for reporting this. The site has been updated. Could you please check if the issue still exists and let us know your response. Closing this for now.

Regards!

**Comment by jancborchardt** [comment]
Yup, the values are now the same as on http://www.asquare.net/javascript/tests/KeyCode.html

- ö is 59
- ä is 222
- ü is 219

However there’s a small issue in the character shown below. For ä it shows `'`, for ü `[`, and for ö (most strangely) it doesn’t change the character.
