### ISSUE TITLE
Implement history

### ISSUE THREAD

**Issue by wesbos** [wesbos/keycodes#307]
For the new version I want to keep a log of recent keys pressed

**Comment by Cool-Runningz** [comment]
Hey @wesbos!  I'm interested in helping out with this feature if it's up for grabs.  Do you have a particular design in mind for how to display the recent keys pressed and is there a cap for how many keys will be saved per session?

Thanks and I look forward to hopefully being able to contribute 🙂

**Comment by wesbos** [comment]
Haven't looked into it yet but it's on the next JS branch, not the master branch. I'd imagine some state, that when the key changes, it's pushed to history. Then we display the last 5 or so. You're welcome to give it a shot!

**Comment by Cool-Runningz** [comment]
Awesome, I'll try and take a look at the Next.js branch and see if I can come up with a decent solution!

**Comment by Cool-Runningz** [comment]
Hey, @wesbos I'm nowhere near feature complete on this but I wanted to provide a quick demo of the things I have toyed around with so far:
![keycodes](https://user-images.githubusercontent.com/6391149/150442163-04214f31-00fa-435a-81c1-1abcd8899026.gif)


**Additional items I'm thinking of adding but wanted to get your opinion on first:**
1. When you click on one of the keys in the history, it will display the detailed information (this is viewable in the demo but can easily be removed)
2.  Remove duplicates from history so that only the last 5 _unique_ keys are shown.

Feel free to tell me to chill out if I'm adding too much scope creep 😅 but these are just some things I thought of while playing around with things.

**Comment by wesbos** [comment]
This looks awesome @Cool-Runningz! Pretty much exactly what I was thinking. 

1. Def be able to click on each one. 
2. Def remove dupes

Otherwise I think thats all we need!

**Comment by wesbos** [comment]
@Cool-Runningz want to submit a PR for this? Totally fine if it's a WIP

**Comment by Cool-Runningz** [comment]
Hey @wesbos apologies for the delay on this one. I made good progress early on and then got sidetracked with other things 😅 I have it on my TODO list to wrap this up soon. Barring any issues, my goal is to try and get a PR out early next week if that works for you.

**Comment by wesbos** [comment]
sounds good! thanks again
